Add quiz management issue 4.5
erykksc/kwikquiz pull request #14
Opened 2024-05-26 21:05 UTC by ducminh02

I think you should have a look at this branch and give me your thought for the pull request before it gets more complicated
So in this feature I have implemented:

- All the buttons for the frontend quiz should work with the backend now, I have also added a delete button for each question when the user is creating a quiz and changed the correct answer format

- moved the script part to a separate js file in static folder

![image](https://github.com/erykksc/kwikquiz/assets/101068929/bfc4c4ca-f78d-40ad-8ec5-1fb92438b00a)

- a quiz is now temporary stored in a hashmap, but I also added another field password so that later we can save it in the database and only users with password can open it because I think storing it in the browser's history or download the format is not very ideal

Ideas for what to implement after this pull request:

- next I want to make the id of the quiz auto generated

- an UI for browsing existing Quizzes

- an UI for a certain existing Quiz so that user can edit it or delete it

- discussion on which database we would like to use and implement it

2024-05-27 20:54 UTC, erykksc commented
I like new structure for the templates and the rest of the changes look good to me.

Please add the following before I accept the changes:
* Merge main branch, as there are conflicts currently
* Add Mutex to the repository, and call it in every repository operation, so that all operations are thread safe (https://pkg.go.dev/sync#Mutex)

2024-05-28 22:52 UTC, ducminh02 commented
@erykksc okay I added auto ID for quizzes, did a few changes and merged main, can you have a look again?

the creation of the quizzes works in the backend, but for some reasons it doesn't show in the temporary frontend.

2024-05-29 04:27 UTC, erykksc requested changes
Switch from JS to HTMX in quiz creation

2024-05-29 04:27 UTC, erykksc commented on static/js/quiz.js
Use HTMX instead of doing it with JS.
The whole point of using HTMX is to not manage the state on the client side.
For example:
* Send multiple requests on user actions, like pressing a button, editing a field...
* You can add more endpoints, some just for a single field validation in a form
* When deleting a question, send a request to the server
* Don't just send one request once submitting (one doesn't even need htmx for that)

Tip: When dealing with multiple elements you can use "range" in templating.

2024-05-29 04:27 UTC, erykksc commented on templates/quizzes/quiz-create.html
Add htmx to it

2024-05-29 16:03 UTC, ducminh02 commented on templates/quizzes/quiz-create.html
I have looked into the switching the implementation for quiz-create template using HTMX, but it will add another layer of complexity when it comes to dynamically generating elements

- for Example:
 when adding a quiz we would still have to declare the quiz counter element in js and then send them as parameter 
 
 hx-params="questionNumber={{ increment }}"
 
 and with that creating the html element in the backend with the arguments and send back. On top of that, we would also need to reset the counter back to 1 with js after the form is submitted.
 
 I would say that for the quiz creation we should manage the state on the client side to avoid adding more complexity to the current situation. What do you think?

2024-06-10 22:09 UTC, erykksc approved these changes
LGTM

2024-06-10 22:09 UTC, merged