Leaderboards of finished games
erykksc/kwikquiz pull request #22
Opened 2024-05-30 16:03 UTC by Eren361

I wanted this to enable users to view leaderboard of a lobby.
I updated lobby, repository and routes. Added a html ui. Added a GetLeaderboard method, created HTTP handler and another method in lobby to return top 3 players.

2024-05-31 00:11 UTC, erykksc requested changes
Generally move the implementation of the past games into "results" package (you need to create it)

2024-05-31 00:11 UTC, erykksc commented on internal/lobby/routes.go
> +	mux.HandleFunc("/lobbies/leaderboard", getLeaderboardHandler)
Move this handler to package "results" (you need to create it) and change the path to "/results/{pin}"

2024-05-31 00:11 UTC, erykksc commented on internal/lobby/repository.go
Lobbies are active games, they are not permanent.
The results of the game will be saved inside the common.Game struct located in "internal/common/types".
So move/adapt the methods from Lobby to Game.

2024-05-31 00:11 UTC, erykksc commented on internal/lobby/lobby.go
> +	Score 	 int
The score for a player is gonna be saved inside "Points" field on common.Game struct located in "internal/common/types".

2024-05-31 00:11 UTC, erykksc commented on internal/lobby/routes.go
> +	}
As stated in other comments, the lobbies are only temporary, implement the Methods like GetLeaderboard on common.Game struct

2024-05-31 00:11 UTC, erykksc commented on internal/lobby/lobby.go
> +}
Lobbies are active games, they are not permanent.
The results of the game will be saved inside the common.Game struct located in "internal/common/types".
So move/adapt the methods from Lobby to Game.

2024-06-05 22:26 UTC, Eren361 commented
> It doesn't compile. Please fix it.

go run "/Users/erenkayakiran/Studium/Praktikum/kwikquiz/cmd/kwikquiz/main.go"
(base) erenkayakiran@Erens-MacBook-Air kwikquiz % go run "/Users/erenkayakiran/Studium/Praktikum/kwikquiz/cmd/kwikquiz/main.go"
time=2024-06-06T00:20:45.204+02:00 level=INFO msg="Server listening" addr=:3000

it compiles by me, can you give more feedback?

2024-06-13 17:56 UTC, closed without merging